imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $tables: '%tables%'
            $ext_images_path: '%core.root_path%ext/david63/announceonindex/adm/style/images'
        public: true			

    david63.announceonindex.listener:
        class: david63\announceonindex\event\listener
        tags:
            - { name: event.listener }

    david63.announceonindex.main.controller:
        class: david63\announceonindex\controller\main_controller

    david63.announceonindex.admin.controller:
        class: david63\announceonindex\controller\admin_controller

    david63.announceonindex.core.functions:
        class: david63\announceonindex\core\functions
